# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ali/APK-Bank-system

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ali/APK-Bank-system

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ali/APK-Bank-system/CMakeFiles /home/ali/APK-Bank-system//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ali/APK-Bank-system/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bank

# Build rule for target.
Bank: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bank
.PHONY : Bank

# fast build rule for target.
Bank/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/build
.PHONY : Bank/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/main.cpp.s
.PHONY : main.cpp.s

src/account.o: src/account.cpp.o
.PHONY : src/account.o

# target to build an object file
src/account.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/account.cpp.o
.PHONY : src/account.cpp.o

src/account.i: src/account.cpp.i
.PHONY : src/account.i

# target to preprocess a source file
src/account.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/account.cpp.i
.PHONY : src/account.cpp.i

src/account.s: src/account.cpp.s
.PHONY : src/account.s

# target to generate assembly for a file
src/account.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/account.cpp.s
.PHONY : src/account.cpp.s

src/bank.o: src/bank.cpp.o
.PHONY : src/bank.o

# target to build an object file
src/bank.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/bank.cpp.o
.PHONY : src/bank.cpp.o

src/bank.i: src/bank.cpp.i
.PHONY : src/bank.i

# target to preprocess a source file
src/bank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/bank.cpp.i
.PHONY : src/bank.cpp.i

src/bank.s: src/bank.cpp.s
.PHONY : src/bank.s

# target to generate assembly for a file
src/bank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/bank.cpp.s
.PHONY : src/bank.cpp.s

src/stock/messageQueue.o: src/stock/messageQueue.cpp.o
.PHONY : src/stock/messageQueue.o

# target to build an object file
src/stock/messageQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/stock/messageQueue.cpp.o
.PHONY : src/stock/messageQueue.cpp.o

src/stock/messageQueue.i: src/stock/messageQueue.cpp.i
.PHONY : src/stock/messageQueue.i

# target to preprocess a source file
src/stock/messageQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/stock/messageQueue.cpp.i
.PHONY : src/stock/messageQueue.cpp.i

src/stock/messageQueue.s: src/stock/messageQueue.cpp.s
.PHONY : src/stock/messageQueue.s

# target to generate assembly for a file
src/stock/messageQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/stock/messageQueue.cpp.s
.PHONY : src/stock/messageQueue.cpp.s

src/stock/server.o: src/stock/server.cpp.o
.PHONY : src/stock/server.o

# target to build an object file
src/stock/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/stock/server.cpp.o
.PHONY : src/stock/server.cpp.o

src/stock/server.i: src/stock/server.cpp.i
.PHONY : src/stock/server.i

# target to preprocess a source file
src/stock/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/stock/server.cpp.i
.PHONY : src/stock/server.cpp.i

src/stock/server.s: src/stock/server.cpp.s
.PHONY : src/stock/server.s

# target to generate assembly for a file
src/stock/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/stock/server.cpp.s
.PHONY : src/stock/server.cpp.s

src/stock/visitor.o: src/stock/visitor.cpp.o
.PHONY : src/stock/visitor.o

# target to build an object file
src/stock/visitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/stock/visitor.cpp.o
.PHONY : src/stock/visitor.cpp.o

src/stock/visitor.i: src/stock/visitor.cpp.i
.PHONY : src/stock/visitor.i

# target to preprocess a source file
src/stock/visitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/stock/visitor.cpp.i
.PHONY : src/stock/visitor.cpp.i

src/stock/visitor.s: src/stock/visitor.cpp.s
.PHONY : src/stock/visitor.s

# target to generate assembly for a file
src/stock/visitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/stock/visitor.cpp.s
.PHONY : src/stock/visitor.cpp.s

src/transaction.o: src/transaction.cpp.o
.PHONY : src/transaction.o

# target to build an object file
src/transaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/transaction.cpp.o
.PHONY : src/transaction.cpp.o

src/transaction.i: src/transaction.cpp.i
.PHONY : src/transaction.i

# target to preprocess a source file
src/transaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/transaction.cpp.i
.PHONY : src/transaction.cpp.i

src/transaction.s: src/transaction.cpp.s
.PHONY : src/transaction.s

# target to generate assembly for a file
src/transaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/transaction.cpp.s
.PHONY : src/transaction.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bank.dir/build.make CMakeFiles/Bank.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Bank"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/account.o"
	@echo "... src/account.i"
	@echo "... src/account.s"
	@echo "... src/bank.o"
	@echo "... src/bank.i"
	@echo "... src/bank.s"
	@echo "... src/stock/messageQueue.o"
	@echo "... src/stock/messageQueue.i"
	@echo "... src/stock/messageQueue.s"
	@echo "... src/stock/server.o"
	@echo "... src/stock/server.i"
	@echo "... src/stock/server.s"
	@echo "... src/stock/visitor.o"
	@echo "... src/stock/visitor.i"
	@echo "... src/stock/visitor.s"
	@echo "... src/transaction.o"
	@echo "... src/transaction.i"
	@echo "... src/transaction.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

